### ISSUE TITLE
fix: scrollbar view and sticky position flickering

### ISSUE THREAD

**Issue by E-Rick** [ourzora/nouns-marketplace#83]
GM! I'm offering some quick style fixes for the `Modal` views and `HorizontalMenu.` 

Add 
```CSS
  msOverflowStyle: 'none',
  scrollbarWidth: 'none',
  '::-webkit-scrollbar': {
      display: 'none',
  },
```
to `background` in `Modal.css.ts` and `modalWrapper` in `Header.css.ts` to remove the side scrollbars. 

So that it goes from

![scrollbars](https://user-images.githubusercontent.com/44077419/184560758-ae5cddba-851f-42d2-a5d5-788485538968.PNG)

To this:

![horizontal](https://user-images.githubusercontent.com/44077419/184560969-79384176-9479-4c2b-85a0-a8cffe246290.PNG)

## Horizontal menu

I took a quick pass at fixing the modal. I had some trouble with fixing the disappearing header but found it easier to work with Radix-UI tab primitives for the horizontal menus. 

I assume `HorizontalMenu` is supposed to function similarly to a Tab menu. So using the Radix UI primitive would simplify the logic and amount of code for `HorizontalMenu` to function properly while adhering to WAI-ARIA accessibility standards. So adding to the design system a Tab component would be ideal. For example, you can look at [Braid](https://seek-oss.github.io/braid-design-system/components/Tabs)'s design system implementation of a tab component. 

This could all be abstracted into something more generic; I hope this was helpful.

```typescript 
// CollectionMenu.tsx
import * as TabsPrimitive from '@radix-ui/react-tabs';
import { tabsButton, tabsList, tabsWrapper } from './CollectionMenu.css';

// Exports
export const Tabs = TabsPrimitive.Root;
export const TabsList = TabsPrimitive.List;
export const TabsTrigger = TabsPrimitive.Trigger;
export const TabsContent = TabsPrimitive.Content;

// Modal render...
...
content={ 
  <Stack as="menu" gap="x6" className={modalWrapper}>
    <Tabs defaultValue={tabs.DAOS} data-orientation='horizontal'>
      <TabsList aria-label='Choose your menu' className={tabsList}>
        <TabsTrigger value={tabs.DAOS} className={tabsButton}>
          <Box as="span" className={label}>
            {tabs.DAOS}
          </Box>
          &nbsp;&nbsp;{daosAmount}
        </TabsTrigger>
        <TabsTrigger value={tabs.COLLECTIONS} className={tabsButton}>
          <Box as="span" className={label}>
            {tabs.COLLECTIONS}
          </Box>
          &nbsp;&nbsp;{collectionAmount}
        </TabsTrigger>
      </TabsList>
      <TabsContent value={tabs.DAOS}>
        <CollectionNavList items={daos} pt='x22' p='x6' />
      </TabsContent>
      <TabsContent value={tabs.COLLECTIONS}>
        <CollectionNavList items={collections} pt='x22' p='x6' />
      </TabsContent>
    </Tabs>
  </Stack>
}
```

```typescript
// CollectionMenu.css.ts

export const tabsButton = style([
  {
    all: 'unset',
    fontFamily: 'inherit',
    backgroundColor: 'white',
    padding: 20,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 20,
    color: vars.color.text.secondary,
    cursor: 'pointer',
    zIndex: 4,
    width: '100%',
    paddingBottom: space.x2,
    borderBottom: `2px solid transparent`,
    selectors: {
      '&:first-child': { borderTopLeftRadius: 40 },
      '&:last-child': { borderTopRightRadius: 40 },
      '&:hover': { borderBottom: `2px solid ${color.black30}` },
      '&[data-state="active"]': {
        color: vars.color.text.primary,
        borderBottom: `2px solid ${color.black70}`,
      },
    }

  },
])


export const tabsList = style([
  {
    display: 'flex',
    position: "absolute",
    width: "100%",
    borderBottom: `2px solid ${color.black10}`,
    zIndex: 4,
  }
])

export const label = style({
  color: vars.color.text.primary
})
```

![horizontal](https://user-images.githubusercontent.com/44077419/184560969-79384176-9479-4c2b-85a0-a8cffe246290.PNG)
![tabsnew](https://user-images.githubusercontent.com/44077419/184579175-c7170fb7-f061-4adb-85ca-7fc6f714d7ea.PNG)

### Sticky Scroll flickering

I would add that `position: sticky` has known flickering problems with scrolling on iOS. I use `position: absolute` or `fixed` to fix the flickering issue in the code above. And I use  `position: absolute` for the `tabList` to test this out.

You can see `filter` and `sort` on the gallery view show the flickering issue when scrolling on iOS devices. I recorded a very short Loom video showing the issue. It doesn't show up on android devices.

https://www.loom.com/share/44879574047446188d120e49b7dee584

**Comment by dblodorn** [comment]
Hey @E-Rick ! this is awesome. Thanks so much for jumping in and surfacing these issues.

If you'd be down for submitting a PR with the above additions would be happy to review further ( :

...And good shout on adding a more efficient (and Aria compliant) tab system to our component library.
this is a great spot to suggest features for zord as well!

**Comment by E-Rick** [comment]
Thanks for the kind words, @dblodorn . I wasn't sure whether to make a PR or not, however I'm glad this was helpful :)
