### ISSUE TITLE
`Error: connector not found` thrown when placing a bid 

### ISSUE THREAD

**Issue by zachuri** [ourzora/nouns-marketplace#96]
## Summary

If a wallet is not connected and someone tries to place a bid this `ERROR: Connector not found` error message is thrown.

While this is technically correct (a connector really isn't there), this may be confusing for casual users who just want to submit a bid. Perhaps this messaging could be updated to be more user-friendly? 🙇‍♂️

<details>

<summary>View Image</summary>

![error-connector-not-found-modal-image](https://user-images.githubusercontent.com/19584918/188223172-2cc7a31f-d735-4d30-b76d-477c9c9df544.png)

</details>

### Steps to reproduce
- go to https://noun.market/ 
- press place bid for the current noun
- specify a value for the bid price and press place bid

Expected behavior: 
- I'd imagine a user friendly message like "Please connect your wallet before submitting a bid"

Actual behavior:
- `ERROR: Connector not found`

**Comment by almndbtr** [comment]
@zachuri and I paired on this earlier today. I was curious about where that bid logic might be. 

Could [`@noun-auction/components/AuctionUi/NounsBidForm.tsx`](https://github.com/ourzora/nouns-marketplace/blob/main/@noun-auction/components/AuctionUi/NounsBidForm.tsx) good be a good place to start for possibly updating the error, specifically:

https://github.com/ourzora/nouns-marketplace/blob/c659d46066e40848e8daf9ce804f0cde573e8761/%40noun-auction/components/AuctionUi/NounsBidForm.tsx#L140

**Comment by bjfresh** [comment]
That would surely be the place. Agreed that experience-wise it makes sense to present user-centric errors as substitutes for generic messaging that's coming from lower in the stack.

I'll surface this with the design team. As we integrate more market modules the pattern for this should be standardized. We should take a step back and consider where in this flow the user should be required to connect with minimal jankiness. The **Place Bid** button in the modal shouldn't be enabled if the user isn't able to place a bid.

Seems to me that the user should be able to launch the bid flow by tapping **Place Bid** within the context of the list of auctions, but once the modal has launched the user should be prompted to connect their wallet.

**Comment by bjfresh** [comment]
Re: user-facing errors, there's functionality for this in use in [formatContractError.ts](https://github.com/ourzora/nouns-marketplace/blob/main/%40shared/utils/formatContractError.ts)

**Comment by almndbtr** [comment]
Sounds great! Once design gives their input, we’d
be open to possibly pitching in a PR if that’s an option 😉 

In any case, we yield to whatever makes the most
sense since this may be a reusable pattern in other parts of this project and/or others. 🫡

**Comment by bjfresh** [comment]
@almndbtr just pushed a PR with a short-term re-jig. Design solutions to these flows forthcoming.

**Comment by almndbtr** [comment]
@bjfresh - Thanks! Now that #103 is shipped, should we go ahead and close this one out?

**Comment by bjfresh** [comment]
@almndbtr yes! Still working with design on a more robust solution. Thanks!
