### ISSUE TITLE
Confirmation message for a successfully placed bid should be updated

### ISSUE THREAD

**Issue by almndbtr** [ourzora/nouns-marketplace#97]
## Summary

https://github.com/ourzora/nouns-marketplace/blob/c659d46066e40848e8daf9ce804f0cde573e8761/%40noun-auction/components/AuctionUi/NounsBidForm.tsx#L162

🔬 `You're` expands to `You are` which isn't correct in context. 

This should be updated to `Your` 😉

**Comment by bjfresh** [comment]
@almndbtr is it possible for that PR to be linked to this repo rather than your fork? 🙏🏼

**Comment by almndbtr** [comment]
Ah yes! Apologies, I misconfigured my target the first time around. Will work on that!
